name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build: 
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login --username nilurova68440  --password "$DOCKERHUB_PASS"
      - name: tipi builds project 
        run: |
         docker build -t nilurova68440/squid_docker .
          docker push nilurova68440/squid_docker
 
