name: build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build: 
    name: build-and-push
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: nilurova68440 
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_PASS"
      - name: tipi builds project 
        run: |
         docker build -t nilurova68440/squid_docker .
          docker push nilurova68440/squid_docker
 
